/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */

import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import org.jetbrains.kotlin.gradle.plugin.KotlinSourceSet
//import com.badlogic.gdx.tools.texturepacker.TexturePacker


plugins {
    java
    idea
    application
    kotlin("jvm") version "1.3.31"
    id("com.github.johnrengelman.shadow") version "2.0.2"
}


group = "o_hej"
version = "0.1.0"

application {
    mainClassName = "main.Main"
}


java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    /*sourceSets {
        main {
            kotlin.srcDir = files("src")
        }
    }*/
}

sourceSets["main"].withConvention(KotlinSourceSet::class) {
    kotlin.srcDir("src")
}


repositories {
    mavenCentral()
    jcenter()
    maven { setUrl("https://oss.sonatype.org/content/repositories/snapshots/") }
    maven { setUrl("https://oss.sonatype.org/content/repositories/releases/") }
}

dependencies {
    compile(kotlin("stdlib"))
    compile(kotlin("reflect"))

    compile("io.github.libktx:ktx-actors:1.9.9-b1")
    compile("com.badlogicgames.gdx:gdx:${properties["gdxVersion"]}")
    compile("com.badlogicgames.gdx:gdx-backend-lwjgl:${properties["gdxVersion"]}")
    compile("com.badlogicgames.gdx:gdx-platform:${properties["gdxVersion"]}:natives-desktop")

    compile("com.badlogicgames.gdx:gdx-freetype:${properties["gdxVersion"]}")
    compile("com.badlogicgames.gdx:gdx-freetype-platform:${properties["gdxVersion"]}:natives-desktop")

    compile("io.github.libktx:ktx-log:${properties["ktxLogVersion"]}")
    compile("io.github.libktx:ktx-scene2d:${properties["ktxScene2DVersion"]}")
    compile("io.github.libktx:ktx-async:${properties["ktxAsyncVersion"]}")
    compile("io.github.libktx:ktx-box2d:${properties["ktxBox2dVersion"]}")
    compile("io.github.libktx:ktx-inject:${properties["ktxInjectVersion"]}")
    compile("io.github.libktx:ktx-app:${properties["ktxAppVersion"]}")
    compile("io.github.libktx:ktx-math:${properties["ktxMathVersion"]}")
    compile("io.github.libktx:ktx-assets:${properties["ktxAssetsVersion"]}")
    compile("io.github.libktx:ktx-i18n:${properties["ktxI18nVersion"]}")
    compile("io.github.libktx:ktx-actors:${properties["ktxActorsVersion"]}")
    compile("io.github.libktx:ktx-collections:${properties["ktxCollectionsVersion"]}")
    compile("io.github.libktx:ktx-style:${properties["ktxStyleVersion"]}")

    //classpath("com.badlogicgames.gdx:gdx-tools:${properties["gdxVersion"]}")
    //classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
}

idea {
    module {
        excludeDirs = setOf(file("target/"))
    }
}

/*

task("gameZip") {
    "shadowJar"()

    from(".")
    include("res/**")

    from("build/libs")
    include("void2*all.jar")

    archiveName("void2.zip")
    destinationDir(file("target/"))
}*/
 */